name: bili_novel_packer
description: A sample command-line application.
version: 0.0.1-beta

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  archive: ^3.3.5
  console: ^4.1.0
  html: ^0.15.1
  http: ^0.13.5
  path: ^1.8.3
  retry: ^3.1.0
  uuid: ^3.0.7
  xml: ^6.2.2
