name: bili_novel_packer
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  archive: ^3.3.5
  http: ^0.13.5
